name: loading_gifs_example
description: An example app to demonstrate loading indicator GIFs.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  loading_gifs:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: