name: loading_gifs
description: Loading indicator GIFs. Material and Cupertino (Android and iOS) loading indicators in assorted sizes. Use as placeholders for loading remote image assets.
version: 0.2.0
homepage: https://codelessly.com
repository: https://github.com/Codelessly/FlutterLoadingGIFs
issue_tracker: https://github.com/Codelessly/FlutterLoadingGIFs/issues
documentation: https://github.com/Codelessly/FlutterLoadingGIFs

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   assets:
     - assets/images/