name: loading_gifs
description: Loading indicator GIFs. Cupertino and Material style loading indicators in various sizes. Placeholder for loading remote image assets.
version: 0.0.1
homepage: https://codelessly.com
repository: https://github.com/Codelessly/FlutterLoadingGIFs
issue_tracker: https://github.com/Codelessly/FlutterLoadingGIFs/issues
documentation: https://github.com/Codelessly/FlutterLoadingGIFs

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   assets:
     - assets/images/
